/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceInstanceSchema {
    #[serde(rename = "create", skip_serializing_if = "Option::is_none")]
    pub create: Option<Box<crate::models::ServiceInstanceSchemaCreate>>,
    #[serde(rename = "update", skip_serializing_if = "Option::is_none")]
    pub update: Option<Box<crate::models::ServiceInstanceSchemaCreate>>,
}

impl ServiceInstanceSchema {
    pub fn new() -> ServiceInstanceSchema {
        ServiceInstanceSchema {
            create: None,
            update: None,
        }
    }
}


