/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceBindingMetadata {
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "renew_before", skip_serializing_if = "Option::is_none")]
    pub renew_before: Option<String>,
}

impl ServiceBindingMetadata {
    pub fn new() -> ServiceBindingMetadata {
        ServiceBindingMetadata {
            expires_at: None,
            renew_before: None,
        }
    }
}


