/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceBindingVolumeMount {
    #[serde(rename = "driver")]
    pub driver: String,
    #[serde(rename = "container_dir")]
    pub container_dir: String,
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "device_type")]
    pub device_type: DeviceType,
    #[serde(rename = "device")]
    pub device: Box<crate::models::ServiceBindingVolumeMountDevice>,
}

impl ServiceBindingVolumeMount {
    pub fn new(driver: String, container_dir: String, mode: Mode, device_type: DeviceType, device: crate::models::ServiceBindingVolumeMountDevice) -> ServiceBindingVolumeMount {
        ServiceBindingVolumeMount {
            driver,
            container_dir,
            mode,
            device_type,
            device: Box::new(device),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "r")]
    R,
    #[serde(rename = "rw")]
    Rw,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceType {
    #[serde(rename = "shared")]
    Shared,
}

